name: CICD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    outputs:
      sha_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test ./src/EMS_BE.sln

      - name: SonarQube scan
        run: |
          dotnet-sonarscanner begin /k:"${{ vars.SONARQUBE_PROJECT_NAME }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ./src/EMS_BE.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Trivy dependency scan
        run: trivy fs ./src > trivy-fs.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set short SHA (image tag)
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.IMAGE_NAME }}:latest
            ${{ vars.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
          context: ./src

      - name: Trivy image scan
        run: trivy image ${{ vars.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }} > trivy-img.txt

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scans
          path: |
            trivy-fs.txt
            trivy-img.txt
          if-no-files-found: error

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Update image tag in values.yaml
        run: |
          yq -i -y '.image.tag = "${{ steps.vars.outputs.sha_short }}"' helmchart/ems-be/values.yaml

      - name: Check if PAT token works
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" https://api.github.com/user
           
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add helmchart/ems-be/values.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.sha_short }} [skip ci]"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:master

  check-db-changes:
    runs-on: self-hosted
    needs: [ci]

    outputs:
      migration_changed: ${{ steps.filter.outputs.migration }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            migration:
              - 'src/Migration/**'

  db-migration:
    runs-on: self-hosted
    needs: [check-db-changes]
    if: needs.check-db-changes.outputs.migration_changed == 'true'
    env:
      ASPNETCORE_ENVIRONMENT: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply migration
        run: cd ./src && dotnet ef database update --project OA.Infrastructure.EF --startup-project EMS_BE
