name: CICD

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test ./src/EMS_BE.sln

      - name: SonarQube scan
        run: |
          dotnet-sonarscanner begin /k:"${{ vars.SONARQUBE_PROJECT_NAME }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ./src/EMS_BE.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Trivy dependency scan
        run: trivy fs ./src > trivy-fs.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.IMAGE_NAME }}:latest
          context: ./src

      - name: Trivy image scan
        run: trivy image ${{ vars.IMAGE_NAME }}:latest > trivy-img.txt

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scans
          path: |
            trivy-fs.txt
            trivy-img.txt
          if-no-files-found: error

  db-migration:
    runs-on: self-hosted
    needs: [ci]
    environment: dev
    env:
      ASPNETCORE_ENVIRONMENT: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply migration
        run: cd ./src && dotnet ef database update --project OA.Infrastructure.EF --startup-project EMS_BE

  cd:
    runs-on: self-hosted
    needs: [db-migration]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS via Helm
        run: |
          helm upgrade --install ems-be ./helmchart/ems-be -n ems --create-namespace \
            --set image.repository=${{ vars.IMAGE_NAME }} \
            --set image.tag=latest \
            --set image.pullPolicy=Always
